# site settings
title: David Alex McClain | Composer
subtitle: Making music that is intimate and imperfect
email: hello@davidalexmcclain.com
description: I’m a Father, Husband, Composer, Musician, and Coder. In varying order.
baseurl:  # the subpath of your site, e.g. /blog
url: https://davidalexmcclain.com
author:
street_address: 
city: 
state: 
zip_code: 
country: 
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: 
  GitLab:
  Google-Plus: 
  Instagram: https://www.instagram.com/davidalexmcclain/
  LinkedIn: 
  Twitter: 
  Facebook: https://fb.me/davidalexmcclain
  Slack:
  Bandcamp: https://davidalexmcclain.bandcamp.com/

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
